### ISSUE TITLE
Command should return error codes instead of true / false

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/grad_meh#15]
If the `gradMehExportMap` command returns false, there is really no way to tell if currently another export process is running or the map is invalid. 
So instead of `true` / `false` the command could return a code.

For example:
`0`: Process started nominally
`1`: Error: Another export is currently running
`2`: Error: Map invalid because `worldSize` in config is missing
`3`: Error: Map invalid because it is packed within a epbo

**Comment by DerZade** [comment]
We'll need the following status codes:

`0`: Process started nominally
`1`: Error: Invalid arguments given
`2`: Error: Another export is currently running
`3`: Error: World not found
`4`: Error: Map invalid because `worldSize` in config is missing
`5`: Error: Map invalid because it is packed within a epbo

**Comment by TheWillard** [comment]
Sounds good 👍
