### ISSUE TITLE
Lythium satellite tile export is corrupted

### ISSUE THREAD

**Issue by indig0fox** [gruppe-adler/grad_meh#34]
For Lythium, the satellite tiles come out distorted. Attached is an 8% scaled mosaic representing the full image, though the distortion is visible in the "sat" images on export as well. The `preview.png` image is fine, also attached below.

```jsonc
{
    "author": "FFAAMOD",
    "version": "0.7.0",
    # ....
    "worldName": "lythium",
    "worldSize": 20480
}
```

![lythium_mosaic](https://user-images.githubusercontent.com/23415303/213862202-d46fab35-64a0-4eee-9a55-816443d5789e.png)
![preview](https://user-images.githubusercontent.com/23415303/213862302-a0e6a0e1-80cc-4068-8e00-567ff526309d.png)

**Comment by TheWillard** [comment]
Thanks for reporting this, it should be fixed in the newest release (v0.7.1).
