### ISSUE TITLE
Intercept doesn't work properly in the main menu

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/grad_meh#4]
All our script run while the main menu display is open. Intercept doesn't like that, so we have to start a mission and then run the export process. 

Best option for that is probably the [`playScriptedMission`](https://community.bistudio.com/wiki/playScriptedMission) command.

**Comment by dedmen** [comment]
> Intercept doesn't like that

huh? why? Only thing I can think of is the eachFrame handler not running, but thats CBA XEH.

**Comment by DerZade** [comment]
cc @TheWillard

**Comment by TheWillard** [comment]
@dedmen Check Intercept Slack

**Comment by TheWillard** [comment]
We can't get a thread lock before pre-init, so we can't do thread stuff in the main menu.
